# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180601_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
