# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20180602_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
