# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-12 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20180602_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
