# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20180621_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='active',
        ),
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
